### ISSUE TITLE
Squeeze excite module? 

### ISSUE THREAD

**Issue by VRandme** [Res2Net/Res2Net-PretrainedModels#16]
The original paper makes use of squeeze and excite modules(se modules).
Certain alternative implementations(https://github.com/4uiiurz1/pytorch-res2net) include them too.

However this repo does not. 
Are there any plans to release official code with the se modules included?

**Comment by gasvn** [comment]
Since se module is not a standard module in common backbone networks such as ResNet and ResNeXt.
To make our backbone network simpler to  use, so we didn't include se module. The se module can be inserted before the short connection of the Res2Net module.

PS: We will release a improved version of Res2Net within the next few weeks. It has more than 2% improvement on ImageNet top-1 acc. (Without using se block and other extra blocks.)

**Comment by gasvn** [comment]
If you have trouble in implementing the se block, I can provide you with the example code.

**Comment by VRandme** [comment]
Thank you very much for the offer! But it is unnecessary.
I primarily use the pytorchimagemodels implementation
(https://github.com/rwightman/pytorch-image-models)
At first thought that that code base did not implement se so I came here for an official implementation. 
Recently I found out that pytorch image models has indeed implemented se module that can be easily used with res2net.

After seeing assembled cnn which used resnet base model to exceed efficientnets in many metrics, I am trying to add res2net into the assembled cnns. 

Anyway I am eager to see your new improved model!
Since it achieves better performance without se, it would no doubt be possible to achieve even better results with se or other channel attention modules. 
I thank you for your effort and look forward to your release!

**Comment by gasvn** [comment]
Res2Net_v1b is now released. Hope you can get better performance with our newly released models.

**Comment by VRandme** [comment]
The new results are very impressive!
However, the paper does not seem to reflect this new changed model.
Is it the same network but with newer datasets augmentation or training?
More information and reproduction information would definitely helpful!

**Comment by gasvn** [comment]
We have added some tricks to improve the network structure. And we use the training method we are working on now to get a better performance. We will release the code once the work is done.
