### ISSUE TITLE
the PretrainedModels is pretrained on imagenet?

### ISSUE THREAD

**Issue by chenbolinstudent** [Res2Net/Res2Net-PretrainedModels#17]
the PretrainedModels is pretrained on imagenet?
thanks.

**Comment by gasvn** [comment]
Yes, they are pretrained on Imagenet.

**Comment by chenbolinstudent** [comment]
they are pretrained on all the Imagenet or the part of it?
which part?
thanks

**Comment by gasvn** [comment]
'pretrained on Imagenet' means that the model is trained on imagenet for classification task.
