### ISSUE TITLE
out = torch.cat((out, self.pool(spx[self.nums])),1) RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 16 and 15 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:87

### ISSUE THREAD

**Issue by chenbolinstudent** [Res2Net/Res2Net-PretrainedModels#19]
out = torch.cat((out, self.pool(spx[self.nums])),1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 16 and 15 in dimension 2 at /pytorch/aten/src/THC/generic/THCTensorMath.cu:87

how to solve it?
thanks

**Comment by gasvn** [comment]
Maybe you should check the input image size.
