### ISSUE TITLE
load model issue

### ISSUE THREAD

**Issue by XiaoHao-Chen** [Res2Net/Res2Net-PretrainedModels#22]
Thank you for your excellent work.
Just like issue 5, I ran into the same problem and added "strict = False" to the solution you gave, but the problem still hasn't been solved and the same error still occurs. I tried to load res2net-50-26w-4s.
Look forward to your reply.
cuda：8.0
python：3.6
pytorch：0.4.0
torchvision：0.1.18

**Comment by gasvn** [comment]
Have you tried to run 'python res2net.py' directly?  Or you can share with me an example code.

**Comment by gasvn** [comment]
https://github.com/Res2Net/Res2Net-PretrainedModels/issues/5#issuecomment-590436928
 maybe this solution can help you.

**Comment by XiaoHao-Chen** [comment]
> [#5 (comment)](https://github.com/Res2Net/Res2Net-PretrainedModels/issues/5#issuecomment-590436928)
> maybe this solution can help you.

I try to solve this problem, but the same mistake will occur.

**Comment by XiaoHao-Chen** [comment]
![5%GZ`930RN7}RXKDBPDU284](https://user-images.githubusercontent.com/46865749/75174147-0b3ebe80-576b-11ea-9da6-8291b63b0acb.png)

**Comment by gasvn** [comment]
It seems that torch0.4.1 is a little different with torch0.4.0.
You can upgrade from torch0.4.0 to torch0.4.1 or higher version to solve this problem.
ref:
https://discuss.pytorch.org/t/solved-unexpected-key-s-in-state-dict-batches-tracked/23884

**Comment by XiaoHao-Chen** [comment]
When I run 'python res2net.py' directly,the same issue will occur. I will try to upgrade the pytorch.
Thank you for your prompt reply.

**Comment by XiaoHao-Chen** [comment]
Updating the version of pytorch can solve the problem.
Thank you.
