### ISSUE TITLE
Will pretrained res2net152-v1b be public?

### ISSUE THREAD

**Issue by splinter21** [Res2Net/Res2Net-PretrainedModels#24]

**Comment by gasvn** [comment]
Training res2net152 takes a lot of time. So you gonna have to wait for several weeks for res2net152_v1b.  We will notify you once res2net152_v1b is released.
We find that the current res2net101_v1b achieves much better results compared with some large models such as resnet152, resnext152, and hrnet48w on many tasks such as classification and instance segmentation, object detection with much less computational cost (about half). Maybe you can try res2net101_v1b for now.

**Comment by hendrycks** [comment]
Will a res2next v1b model be made available?

**Comment by hendrycks** [comment]
I ask because the v1b models seem like an even bigger contribution than the original res2net proposal, so I'm especially interested in v1b weights.

**Comment by gasvn** [comment]
We have trained the res2net152, and we are benchmarking it on downstream tasks. If everything goes right, you can expect the res2net152 within a week. Thanks for your interest and patience.

**Comment by hendrycks** [comment]
Are you intending to write a paper for Res2Net v1b? I'm finding it substantially much more robust to distribution shift than Res2Net and ResNet.

**Comment by gasvn** [comment]
The res2net_v1b_152 is now available on https://mailnankaieducn-my.sharepoint.com/:u:/g/personal/shgao_mail_nankai_edu_cn/ERLs1nrRZepNumQ0GQEYEpwBRnqByInWTjvZLzhlc2blSw?e=cbr0cZ 
Due to the overfiting of too deep model, the top.1 error of res2net152_v1b is similar to the res2net101_v1b. We are still working on avoiding the overfiting. We will release a new version once we solve the overfiting problem.
 Still, res2net_v1b_152 achieves better performance on downstream tasks such as object detection.

**Comment by gasvn** [comment]
> Are you intending to write a paper for Res2Net v1b? I'm finding it substantially much more robust to distribution shift than Res2Net and ResNet.

Thanks for your feedback!
Res2Netv1b have some slight improvements compared with res2net. We are still working on the improvement of this version. Once everything is done, we will release a report or a paper.

**Comment by hendrycks** [comment]
> Still, res2net_v1b_152 achieves better performance on downstream tasks such as object detection.
Yes, it also had better downstream performance than Res2Netv1b 101 on robustness tasks.

**Comment by hendrycks** [comment]
If you have code for a Res2NeXt v1b and need a model trained, I might be able to train a Res2NeXt v1b for you.
