### ISSUE TITLE
how  i use the Res2Net in res2Net-maskrcnn

### ISSUE THREAD

**Issue by RLiBIn** [Res2Net/Res2Net-PretrainedModels#26]
Iam interested in your success,I want to reproduce this project and find inspiration from it .can you provide detailed steps,Thanks.

**Comment by gasvn** [comment]
Thanks for your interest. You can refer to this repo for the reproduction of res2net-maskrcnn: https://github.com/Res2Net/Res2Net-maskrcnn

**Comment by RLiBIn** [comment]
I am sorry.i can't reproduce this project https://github.com/Res2Net/Res2Net-maskrcnn,it happen some error.
size mismatch for backbone.body.layer4.2.conv3.weight: copying a param with shape torch.Size([2048, 896, 1, 1]) from checkpoint, the shape in current model is torch.Size([2048, 512, 1, 1]).

**Comment by gasvn** [comment]
Please refer to this issue: https://github.com/Res2Net/Res2Net-maskrcnn/issues/1#issuecomment-596181262
