### ISSUE TITLE
load pretrain model issue

### ISSUE THREAD

**Issue by zzzmm1** [Res2Net/Res2Net-PretrainedModels#29]
RuntimeError: Error(s) in loading state_dict for Res2Net:
	size mismatch for layer1.0.downsample.1.weight: copying a param of torch.Size([256]) from checkpoint, where the shape is torch.Size([256, 64, 1, 1]) in current model.
	size mismatch for layer2.0.downsample.1.weight: copying a param of torch.Size([512]) from checkpoint, where the shape is torch.Size([512, 256, 1, 1]) in current model.
	size mismatch for layer3.0.downsample.1.weight: copying a param of torch.Size([1024]) from checkpoint, where the shape is torch.Size([1024, 512, 1, 1]) in current model.

when i load res2net50_v1b.pth,  i meet this problem, but i can load res2net50_26w_4s.pth pretrain model to train my network.
i guess there is a problem between pytorch version?

pytorch: 0.4.1;
torchvision: 0.2.1
python: 3.6

**Comment by gasvn** [comment]
I guess so. Maybe you can try pytorch>1.0, those models are not trained with pytorch0.4.1.

**Comment by gasvn** [comment]
If the problem still exists, please let me know.

**Comment by zzzmm1** [comment]
I use pytorch 1.4.0 and the problem still exists.

**Comment by gasvn** [comment]
Do you use the res2net_v1b.py file? Or do you add res2net to your existing model? The downsample module in res2netv1b is silightly differenet from res2netv1 and resnet. 
You can sent your code to me via email shgao@live.com , maybe I can help you find the problem.

**Comment by zzzmm1** [comment]
I did not use the res2net_v1b.py file, that's the problem. 
Now it is ok, thank you for your help.
