### ISSUE TITLE
difference between res2net and res2net_v1b

### ISSUE THREAD

**Issue by breezelj** [Res2Net/Res2Net-PretrainedModels#31]
thank your amazing work.
compared with original version of Res2Net, res2net_v1b make two difference:
1.replace conv 7*7 with [this](https://github.com/Res2Net/Res2Net-PretrainedModels/blob/master/res2net_v1b.py#L101)
2.downsample replace conv(stride=2) with avgpool2d [this](https://github.com/Res2Net/Res2Net-PretrainedModels/blob/master/res2net_v1b.py#L131)

after changing these， Res2Net_v1b has more than 2% improvement on ImageNet top1 acc. compared with original version of Res2Net
am I right? thank your reply

**Comment by gasvn** [comment]
In addition to the structure change as you mentioned, we have also improved the training strategy.

**Comment by breezelj** [comment]
thanks，will the training strategy be released？ （If not convenient, feel free to close this issue）

**Comment by gasvn** [comment]
It will be released. But for now, we are still working on improving the training strategy.

**Comment by breezelj** [comment]
ok, I am looking forward it
