### ISSUE TITLE
Some Questions about other network

### ISSUE THREAD

**Issue by UestcJay** [Res2Net/Res2Net-PretrainedModels#32]
thank your amazing work.
Can the deep separable convolution of mobilenet merge with the idea of Res2Net? Will it improve？

**Comment by gasvn** [comment]
The hierarchical residual-like connections  in res2net have been proved useful in many tasks. As far as I know, some works have use the separable convolution and res2net module structure to achieve highly efficient network. So I think it will functional on mobilenet. Maybe you can conduct a experiment and let know if there is a improvement.

**Comment by UestcJay** [comment]
Thank you very much for your reply. Can you tell me which work combines separated convolution and Res2net, I want to refer to it. I tried to modify my own convolution network, but still failed

**Comment by gasvn** [comment]
> Thank you very much for your reply. Can you tell me which work combines separated convolution and Res2net, I want to refer to it. I tried to modify my own convolution network, but still failed
Sorry for the late reply, have you find the solution?
