### ISSUE TITLE
top-1 error	top-5 error

### ISSUE THREAD

**Issue by henbucuoshanghai** [Res2Net/Res2Net-PretrainedModels#34]
在imagenet上训练，在哪里得到top-1 error | top-5 error

code在哪里呢？

**Comment by gasvn** [comment]
You can refer to this repo for testing: https://github.com/pytorch/examples/tree/master/imagenet

**Comment by henbucuoshanghai** [comment]
训练代码测试代码统统是连接吗？

**Comment by henbucuoshanghai** [comment]
链接里面有训练代码吗？

**Comment by gasvn** [comment]
We use an older version of this code to train our model. The new training code from this link may be more efficient. I didn't test the current code, but it should have the same performance compared with the old code.

**Comment by henbucuoshanghai** [comment]
in that code,all i have to  do is only change the "model" to   res2net50 in     res2net.py/res2net_v1b.py/res2next.py in this git?????
