### ISSUE TITLE
Confused on tensor splitting

### ISSUE THREAD

**Issue by koyakuwe** [Res2Net/Res2Net-PretrainedModels#35]
In line [here](https://github.com/Res2Net/Res2Net-PretrainedModels/blob/d56af39dfc977bcbf3216871d20e2a9e16801c8a/res2net.py#L70), you split the input tensor based on the number of `width`, but I am expecting it should be based on `scale`. Am I missing something? Also, you process 1st split/group with `conv` and `bn` while your paper said that "_To reduce the number of parameters, we omit the convolution for the first split, which can also be regarded as a form of feature reuse._". Could you enlighten me?

EDIT: for first question, I get it now (I was confused about "the number" vs "the size" in `torch.split`)
EDIT2: got it, turns out conv is not applied in last input

Thanks!

**Comment by drcege** [comment]
For the first question,  how do you get 26 as the baseWidth?
