### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by swjtulinxi** [Res2Net/Res2Net-PretrainedModels#37]
self.nums = scale -1请问你论文是分的4组吧，
你代码为什么又分的三组呢

**Comment by wangbin2018** [comment]
你看后面for i in range(self.nums):    所以0，1，2，3不就是四组

**Comment by swjtulinxi** [comment]
self.nums = scale -1，但是你前面是nums等于3啊，所以是0，1，2吧

width = int(math.floor(planes * (baseWidth/64.0)))
你这里假设planes=256，你的basewidth设置的26，那么width就等于104，
spx = torch.split(out, self.width, 1)
那么就分成，104，104，48不是吗，这里也没有4份啊，求解释一下，我研究半天了，还是没弄明白啊

**Comment by gasvn** [comment]
Suppose there are 4 groups. Then three groups are hierarchically connected, and one group is linked to the output without processing.
![image](https://user-images.githubusercontent.com/20515144/86422753-9418c880-bd10-11ea-916c-dc8f29842b59.png)
