### ISSUE TITLE
training hyperparameter

### ISSUE THREAD

**Issue by wangbin2018** [Res2Net/Res2Net-PretrainedModels#38]
Hello，where can I see the training Hyperparameter？

**Comment by gasvn** [comment]
You can refer to this repo to reproduce our results. https://github.com/pytorch/examples/blob/master/imagenet/main.py

**Comment by wangbin2018** [comment]
I train the res2net-v1b about 200 epochs,but only get top1-78.37%,(lr = 0.2 ,per_batch = 128 on 8 GPU), other hyperparameter is same，about 2% less，how can I adjustment?

**Comment by wangbin2018** [comment]
Excuse me，can I ask one more question？You paper say use a mini-batch of 256 on 4 Titan Xp GPUs，256 is total batch (means 64 per GPU)or 256 per GPU, and the Hyperparameter of res2net_v1b is the same as res2net?

**Comment by gasvn** [comment]
The v1b uses our designed trick that is similar to mixup. Sorry I cannot give it to you since we are still working on it. Using mixup and coslr with 300 epoch can get the similar result. If you are going to compare your method with res2net, you can just refer to the results in the paper.

**Comment by wangbin2018** [comment]
Thank you very much!So common version of res2net using trick? And do you train net using f16, because 256 per_batch can lead to OOM. I'm very interest in your work~

**Comment by gasvn** [comment]
The res2net_v1b is  designed for better downstream task, not for comparison. I didn't use f16, and no OOM happens when using GPU with 11G memory.
