### ISSUE TITLE
v1d

### ISSUE THREAD

**Issue by michaelschleiss** [Res2Net/Res2Net-PretrainedModels#39]
In the original mmdetection repository I am reading something about res2net_v1d (e.g. [here](https://github.com/open-mmlab/mmdetection/blob/master/configs/res2net/cascade_rcnn_r2_101_fpn_20e_coco.py)). I cannot find any information about a v1d in your repo. Is this just a typo or is it a different version from this repo?

**Comment by gasvn** [comment]
The res2net_v1d in mmdetection is the res2net_v1b in our repo. The only difference is that we change the name of stem layers to match the config in mmdetection. The weights of res2net_v1d  and res2net_v1b is exactly the same. The mmdetection team somehow changed the name.
