### ISSUE TITLE
res2net50 mmdetection v2

### ISSUE THREAD

**Issue by dereyly** [Res2Net/Res2Net-PretrainedModels#40]
I love to use res2net in mmdetection
How can i convert pretrained res2net from mmdetection v1 to v2
I want to train res2net50 and convert some my experiments from  v1.1

**Comment by gasvn** [comment]
What is v1.1? Do you mean res2net_v1b? If you want to convert res2net_v1b to the pretrained model used in mmdetection v2, you can refer to this code:
https://github.com/Res2Net/mmdetection/blob/mmdetv1_res2net/tools/detectron2pytorch.py
You may need a few modifications according to res2net.
