### ISSUE TITLE
MMDetection v2里的Res2Net是Res2Net_v1b版本的吗？

### ISSUE THREAD

**Issue by XianYuZhiWang** [Res2Net/Res2Net-PretrainedModels#42]
MMDetection v2里的Res2Net是Res2Net_v1b版本的吗？

**Comment by gasvn** [comment]
Yes

**Comment by LiGithubYu** [comment]
> Yes

提供的Res2Net-v1b-50预训练模型与mmdetection不完全匹配 请问如何修改

**Comment by gasvn** [comment]
> > Yes
> 
> 提供的Res2Net-v1b-50预训练模型与mmdetection不完全匹配 请问如何修改
Res2Net-v1b-50根据mmdetection的要求修改了部分命名（例如conv1）。如果你不需要重新训练，可以直接加载mmdetection里面的res2net pretrain，如果你需要重新训练，可以下载mmdetection的pretrain然后根据它的命名修改一下

**Comment by LiGithubYu** [comment]
> > > Yes
> > 
> > 
> > 提供的Res2Net-v1b-50预训练模型与mmdetection不完全匹配 请问如何修改
> > Res2Net-v1b-50根据mmdetection的要求修改了部分命名（例如conv1）。如果你不需要重新训练，可以直接加载mmdetection里面的res2net pretrain，如果你需要重新训练，可以下载mmdetection的pretrain然后根据它的命名修改一下

thanks
