### ISSUE TITLE
1. res2net152_v1b_26w_4s has no pre-trained model 2.

### ISSUE THREAD

**Issue by JiangMei0201** [Res2Net/Res2Net-PretrainedModels#43]
Thanks for your great job and contribution!  
1. I noticed that in res2net_v1.py，res2net152_v1b_26w_4s function didn’t has pre-trained model. like this:
 
--> 212         model.load_state_dict(model_zoo.load_url(model_urls['res2net152_v1b_26w_4s']))
    213     return model
    214 

KeyError: 'res2net152_v1b_26w_4s'

2.  In README.md, Input image should be normalized. But in res2net_v1.py, it don't use Input image normalized. As follows:

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                  std=[0.229, 0.224, 0.225])

images = torch.rand(1, 3, 224, 224).cuda(0)
model = res2net50_v1b_26w_4s(pretrained=True)
model = model.cuda(0)
print(model(images).size())

Thanks for your help

**Comment by gasvn** [comment]
We didn't host the pretrained model of res2net_v1b_152 on the cloud, you can download it with this link:
 https://mailnankaieducn-my.sharepoint.com/:u:/g/personal/shgao_mail_nankai_edu_cn/ERLs1nrRZepNumQ0GQEYEpwBRnqByInWTjvZLzhlc2blSw?e=cbr0cZ

The normalization of res2net_v1 and res2net_v1b is the same. We didn't normalize the input image within the model, you need to add the normalization by yourself.
