### ISSUE TITLE
pretraindedModels without aspp's state_dict

### ISSUE THREAD

**Issue by ActonMartin** [Res2Net/Res2Net-PretrainedModels#47]
I try to restore parts of the state_dicts that you supply in the code repository but don't have aspp's state_dict. Could you supply any segmentation's pretrained model?

**Comment by gasvn** [comment]
Res2Net has no aspp module. If you do the segmentation task with Res2Net, only the weights in Res2Net are initialized with ImageNet pretraining, the weights in ASPP can be initialized with no ImageNet pretraining.
