### ISSUE TITLE
请问三个版本之间有什么区别，哪个是最新的

### ISSUE THREAD

**Issue by LiGithubYu** [Res2Net/Res2Net-PretrainedModels#49]
请问res2net、res2net_v1b、res2next之间有什么区别，哪个是最新的

**Comment by gasvn** [comment]
res2net_v1b is a improved version of res2net, which follows  the structure of resnet_v1d and has better training scheme.
Res2NeXt is based on the ResNeXt.
res2net_v1b has the best performance.

**Comment by chenpeng68** [comment]
res2net_v1b在res2net基础具体上修改了哪些呢

**Comment by gasvn** [comment]
> res2net_v1b在res2net基础具体上修改了哪些呢
我们follow resnet_v1b修改了input的conv和downsample block
