### ISSUE TITLE
stype=stage with AveragePooling - mentioned in paper?

### ISSUE THREAD

**Issue by cgebbe** [Res2Net/Res2Net-PretrainedModels#53]
According to the code, there is a parameter stype. If stype=='stage', there will be no additive connections. Moreover, an average pooling layer is applied to the last "slice", see https://github.com/Res2Net/Res2Net-PretrainedModels/blob/12dbee5abc92eaa270c0f972a398fa6a3bccd8b9/res2net.py#L85

In https://github.com/Res2Net/Res2Net-PretrainedModels/issues/11 you mention that stype=='stage' refers to the three downsampling blocks in the resnet architecture.

Is this parameter and the removal of the additive connections mentioned anywhere in the paper? Has it always been there or does it represent a new variation?

**Comment by gasvn** [comment]
The hierarchical residual-like connections in Res2Net require the input and output features to have the same resolution. So when facing the downsampling, we remove the hierarchical connections in Res2Net block. This design choice is not a new variation. In the paper, we didn't  focus on this point as it has no connection with our motivation in the proposed Res2Net block. The overall network structure (channel number, stage number, block number in each stage) is mostly based on the resnet structure.
