### ISSUE TITLE
感受野的问题

### ISSUE THREAD

**Issue by wangziyan1234** [Res2Net/Res2Net-PretrainedModels#55]
![11](https://user-images.githubusercontent.com/48083793/111023889-8b879e80-8416-11eb-9861-db6b5c55ba8a.png)
如图，当x4经过运算后，得到的y4的感受野会变大么？ 对x4进行卷积时的stride为1，特征大小并没缩小，讲道理应该不会增大感受野吧，文章说会增大，于是有点疑惑，可能是我自己也么太理解，希望大佬答疑，谢谢拉
![12](https://user-images.githubusercontent.com/48083793/111024008-49ab2800-8417-11eb-841b-514b10da651c.png)

**Comment by gasvn** [comment]
c

**Comment by wangziyan1234** [comment]
您说的有道理， 但是我脑子还是有点转不过来&nbsp; &nbsp; x2经过K2 K3 K4 ，但是stride=1&nbsp; &nbsp; 假如 x2的特征尺寸为12x12&nbsp; 那么经过K2 K3 K4还是为12x12&nbsp; &nbsp;那感受野应该没变呀&nbsp; &nbsp; 是不是我对感受野没理解清楚。。。&nbsp; &nbsp;还请您指点指点




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Res2Net/Res2Net-PretrainedModels"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月14日(星期天) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Res2Net/Res2Net-PretrainedModels] 感受野的问题 (#55)





 
举例来说，x2 的feature可以经过与K2,K3,K4,所以感受野可以变大。x4确实只有3x3卷积的感受野，但是x2，x3的最终感受野经过K4会变大。

**Comment by wangziyan1234** [comment]
&nbsp; 是空格   好像乱码了

**Comment by gasvn** [comment]
感受野除了通过stride>1来增大，也可以通过卷积核>1来增大， kernel=3的时候，每经过一层卷积，感受野会逐渐增大

**Comment by wangziyan1234** [comment]
哦哦哦&nbsp; &nbsp;多谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shanghua ***@***.***&gt;; 
发送时间: 2021年3月14日(星期天) 晚上8:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Res2Net/Res2Net-PretrainedModels] 感受野的问题 (#55)





 
感受野除了通过stride&gt;1来增大，也可以通过卷积核&gt;1来增大， kernel=3的时候，每经过一层卷积，感受野会逐渐增大
