### ISSUE TITLE
Can res2net have a basic block structure? 

### ISSUE THREAD

**Issue by Buildernet** [Res2Net/Res2Net-PretrainedModels#60]
Thank you for your excellent work ，can res2net have a basic block structure?

**Comment by gasvn** [comment]
The basic block of res2net is in the Bottle2neck block of code https://github.com/Res2Net/Res2Net-PretrainedModels/blob/master/res2net_v1b.py

**Comment by Buildernet** [comment]
![1](https://user-images.githubusercontent.com/41811026/125588661-bd8f7507-3903-4b32-a6b1-5a8c56ae5449.png)
I mean can it have such this structure? As shown the figure

**Comment by gasvn** [comment]
![image](https://user-images.githubusercontent.com/20515144/125589185-97dad31c-dd2e-4473-b3b8-435c73897e8d.png)
For more detailed structure, you can generate by yourself.

**Comment by Buildernet** [comment]
thank you

**Comment by Yhj252525564** [comment]
The code is all pre-trained models. Is there any initial code?

**Comment by gasvn** [comment]
> The code is all pre-trained models. Is there any initial code?

You can reproduce our results with https://github.com/Res2Net/Res2Net-ImageNet-Training
