### ISSUE TITLE
Res2Net object detection

### ISSUE THREAD

**Issue by stanislavkuskov** [Res2Net/Res2Net-PretrainedModels#61]
Hello @gasvn ! Thank You for Your great work! 
What layers (outputs) do you think are the best to use for object detection in the res2net architecture? What  (outputs) layers do you use as inputs for faster-rcnn, mask-rcnn, ssd?

**Comment by gasvn** [comment]
sorry I missed your comments. Res2Net uses the same layers as resnet for object detection methods.

**Comment by stanislavkuskov** [comment]
Hi @gasvn ! I'm already figured out in layers)) Thank You!
