### ISSUE TITLE
What is baseWidth?

### ISSUE THREAD

**Issue by udkii** [Res2Net/Res2Net-PretrainedModels#64]
Hello. I have a question about Res2Net. 

I don't understand what is the 'baseWidth'. When we make Cottle2neck class and Res2Neet class, I can see baseWidth=26 at def__init__. And baseWidth is described as basic width of conv3*3.

What does basic width of convolution mean? Isn't the size of a 3*3 convolution layer 3*3?

I wonder where 26 comes from. Looking at the size of bn1.bias of Res2Net, torch.Size([104]) is output. This 104 is the value of baseWidth(26)*scale(4). What the heck is this baseWidth?

There seems to be no size 104 in the bottleneck of ResNet50. 
I need some advices. Can anybody help me?

Thank you.

**Comment by gasvn** [comment]
baseWidth is a multiplier to make sure the parameters of Res2Net is similar to ResNet.

**Comment by Dream-ai** [comment]
I also had the same problem

**Comment by Liqq1** [comment]
> baseWidth is a multiplier to make sure the parameters of Res2Net is similar to ResNet.
您好，我想问一下 /64 再*plane 的作用是什么？ 为什么不直接 用 26*scale？
