### ISSUE TITLE
About stype.stage

### ISSUE THREAD

**Issue by Liqq1** [Res2Net/Res2Net-PretrainedModels#65]
Hi
Could you please explain the meaning of 'stage' for me in more detail? Is it not used in the entire Res2Net network？
` type: 'normal': normal set. 'stage': first block of a new stage.`

**Comment by gasvn** [comment]
The normal block is the exact res2net block, and the stage block is the res2net block without shortcut inside bacause the feature shape changes for each block of a new stage.

**Comment by Liqq1** [comment]
> The normal block is the exact res2net block, and the stage block is the res2net block without shortcut inside bacause the feature shape changes for each block of a new stage.

感谢回复
另外还有一个问题就是，为什么对于stype=='stage‘的时候不用加上前一小块的输出结果，而是直接 sp = spx[i]呢？

<img width="670" alt="image" src="https://user-images.githubusercontent.com/54054113/156296779-7eaa5e3d-2e8b-4671-a01b-29adcac450d2.png">

**Comment by gasvn** [comment]
> > The normal block is the exact res2net block, and the stage block is the res2net block without shortcut inside bacause the feature shape changes for each block of a new stage.
> 
> 感谢回复 另外还有一个问题就是，为什么对于stype=='stage‘的时候不用加上前一小块的输出结果，而是直接 sp = spx[i]呢？
> 
> <img alt="image" width="670" src="https://user-images.githubusercontent.com/54054113/156296779-7eaa5e3d-2e8b-4671-a01b-29adcac450d2.png">

因为输入输出特征的尺寸不一致，所以没法直接加起来
