### ISSUE TITLE
How to determine the width parameter

### ISSUE THREAD

**Issue by drcege** [Res2Net/Res2Net-PretrainedModels#66]
May I ask how to determine the width parameter `w`? 

For example in Table 3, `Res2Net-50 (Preserved complexity)` of settings `48wx2s`, `26w×4s`, and `14w×8s` have the same FLOPs as `ResNet-50` of `64w`. 
How did you get the values 48, 26, and 14? Can you share the calculation formula?

**Comment by gasvn** [comment]
We adjuct the width of models with each scale to make the overall parameters and FLOPS constant with resnet-50. It's easy to keep the Flops as the overall structure is not changed.
