### ISSUE TITLE
About ResNet18？

### ISSUE THREAD

**Issue by Rashfu** [Res2Net/Res2Net-PretrainedModels#67]
Have you tried this structure on ResNet18? Does it work for light-weight network?

**Comment by gasvn** [comment]
Sorry, we don't have Res2Net models smaller than resnet50. The res2net should also work for resnet18 as it improve the model multi-scale ability from a fine-grained level.

**Comment by Rashfu** [comment]
Theoretically, it works for resnet18. How do you get Res2Net pretrained models, trained from scratch on ImageNet for 100 epoches?

**Comment by gasvn** [comment]
Yes, by default we train the model on imagenet for 100 epochs.
