### ISSUE TITLE
张量尺寸不匹配问题

### ISSUE THREAD

**Issue by kirkzZ** [Res2Net/Res2Net-PretrainedModels#68]
你好请问
for i in range(self.nums):
if i==0 or self.stype=='stage':
sp = spx[i]
else:
sp = sp + spx[i] //这里因为两个特征的尺寸不一样并不能加在一起啊？一个是64一个是128

**Comment by gasvn** [comment]
是的，如果你使用了stride=2的conv导致特征尺寸不一样，res2net module默认退化成group conv的形式。你也可以考虑用pooling的方式对齐特征尺寸
